package:
   name: cudatoolkit
   version: 7.5

build:
  number: 4
  script_env:
    - NVTOOLSEXT_INSTALL_PATH

requirements:
  build:
    - python >=3
    - requests
    - 7za # [win]
    - conda
    - pyyaml
  run:
    - cudart 7.5.*
    - cublas 7.5.*
    - cufft 7.5.*
    - curand 7.5.*
    - cusparse 7.5.*
    - cusolver 7.5.*
    - npp 7.5.*
    - nvblas 7.5.*
    - nvrtc 7.5.*
    - nvvm 7.5.*
    - cupti 7.5.*

outputs:
  - name: cudart
    requirements:
      build:
        - python >=3
        - requests
        - 7za # [win]
        - conda
        - pyyaml
    source:
      path: ../scripts/
    script: bld.bat # [win]
    script: bld.sh # [not win]
  - name: cublas
    requirements:
      build:
        - python >=3
        - requests
        - 7za # [win]
        - conda
        - pyyaml
      run:
        - cudart 7.5.*
    source:
      path: ../scripts/
    script: bld.bat # [win]
    script: bld.sh # [not win]
  - name: cufft
    requirements:
      build:
        - python >=3
        - requests
        - 7za # [win]
        - conda
        - pyyaml
      run:
        - cudart 7.5.*
    source:
      path: ../scripts/
    script: bld.bat # [win]
    script: bld.sh # [not win]
  - name: curand
    requirements:
      build:
        - python >=3
        - requests
        - 7za # [win]
        - conda
        - pyyaml
      run:
        - cudart 7.5.*
    source:
      path: ../scripts/
    script: bld.bat # [win]
    script: bld.sh # [not win]
  - name: cusparse
    requirements:
      build:
        - python >=3
        - requests
        - 7za # [win]
        - conda
        - pyyaml
      run:
        - cudart 7.5.*
    source:
      path: ../scripts/
    script: bld.bat # [win]
    script: bld.sh # [not win]
  - name: npp
    requirements:
      build:
        - python >=3
        - requests
        - 7za # [win]
        - conda
        - pyyaml
      run:
        - cudart 7.5.*
    source:
      path: ../scripts/
    script: bld.bat # [win]
    script: bld.sh # [not win]
  - name: cusolver
    requirements:
      build:
        - python >=3
        - requests
        - 7za # [win]
        - conda
        - pyyaml
      run:
        - cublas 7.5.*
        - cusparse 7.5.*
    source:
      path: ../scripts/
    script: bld.bat # [win]
    script: bld.sh # [not win]
  - name: nvblas
    requirements:
      build:
        - python >=3
        - requests
        - 7za # [win]
        - conda
        - pyyaml
      run:
        - cublas 7.5.*
    source:
      path: ../scripts/
    script: bld.bat # [win]
    script: bld.sh # [not win]
  - name: nvrtc
    requirements:
      build:
        - python >=3
        - requests
        - 7za # [win]
        - conda
        - pyyaml
      run:
        - cudart 7.5.*
    source:
      path: ../scripts/
    script: bld.bat # [win]
    script: bld.sh # [not win]
  - name: nvvm
    requirements:
      build:
        - python >=3
        - requests
        - 7za # [win]
        - conda
        - pyyaml
      run:
        - cudart 7.5.*
    source:
      path: ../scripts/
    script: bld.bat # [win]
    script: bld.sh # [not win]
  - name: cupti
    requirements:
      build:
        - python >=3
        - requests
        - 7za # [win]
        - conda
        - pyyaml
      run:
        - cudart 7.5.*
    source:
      path: ../scripts/
    script: bld.bat # [win]
    script: bld.sh # [not win]


source:
  path: ../scripts/

test:
  requires:
    - numba
